# Generated by Django 4.1.3 on 2022-12-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221227_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_all_users', 'Can view all users')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
