# Generated by Django 4.1.3 on 2022-11-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.trackerstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.trackertype', verbose_name='Тип'),
        ),
    ]
