# Generated by Django 4.1.3 on 2022-11-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_tracker_status_alter_tracker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='type',
        ),
        migrations.AddField(
            model_name='tracker',
            name='type_old',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.trackertype', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
