# Generated by Django 4.1.3 on 2022-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_tracker_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.trackertype'),
        ),
    ]
