# Generated by Django 4.1.3 on 2022-11-25 08:05

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_tracker_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.validate.at_least_10], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(related_name='tasks_new', to='webapp.trackertype'),
        ),
    ]
