# Generated by Django 4.1.3 on 2022-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_tracker_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(related_name='tasks_new', to='webapp.trackertype'),
        ),
    ]
