# Generated by Django 4.1.3 on 2022-11-25 08:11

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_tracker_description_alter_tracker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.validate.MinLengthValidator(6)], verbose_name='Краткое описание'),
        ),
    ]
