# Generated by Django 4.1.3 on 2022-12-06 07:35

from django.db import migrations, models
import django.db.models.deletion

from webapp.models import Project


def test_project(apps, schema_editor):
    new_project = Project(
        title = 'Test'
    )
    new_project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_tracker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RunPython(test_project),
        migrations.AddField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
