# Generated by Django 4.1.3 on 2022-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_tracker_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='type',
            field=models.ManyToManyField(null=True, related_name='tasks_new', to='webapp.trackertype'),
        ),
    ]
