# Generated by Django 4.1.3 on 2022-12-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='webapp_project',
        ),
    ]
