# Generated by Django 4.1.3 on 2022-12-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_users_to_the_project', 'Can add users to project'), ('can_delete_users_to_the_project', 'Can delete users in projects')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
