# Generated by Django 4.1.3 on 2022-12-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_users_to_the_project', 'Can add users to project'), ('can_delete_users_to_the_project', 'Can delete users in projects'), ('can_view_all_users', 'Can view all users')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
